name: Run-BZM-GUI-Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        poetry-version: 1.4.2  # Specify a compatible Poetry version

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      env:
        BZM_API_KEY: ${{ secrets.BZM_API_KEY }}
        BZM_API_SECRET: ${{ secrets.BZM_API_SECRET }}
      run: poetry run pytest
